# UKG to CMiC Integration Middleware
This python project pulls time entry data from UKG Time Management (UTM) along with associated employee information, transforms it into the necessary format for upload to CMiC pytimesheets, and posts the entries. Check log files for errors.

In [8]:
import pandas as pd
from datetime import datetime
from pay_period import find_period_by_date,payRuntoPayGroup

selectionDate = datetime(2026,7,24)
#B or W for biweekly or weekly payruns
payRun = 'B'
createPerDiemEntry = True
PAYGROUPID = payRuntoPayGroup[payRun]
pay_period_file = "DataFiles/Pay_Period.csv"
df = pd.read_csv(pay_period_file, skiprows=2)

period_df = find_period_by_date(df,payRun,selectionDate)
startdate = period_df['Start Date'].iloc[-1]
enddate = period_df['End Date'].iloc[-1]
paydate = enddate + pd.Timedelta(days=6)
period_control = paydate.strftime("%Y%m%d") + "1"
print(f"{startdate=}, {enddate=},{period_control=}, {payRun=}, {PAYGROUPID=}")
period_df

startdate=Timestamp('2026-07-12 00:00:00'), enddate=Timestamp('2026-07-25 00:00:00'),period_control='202607311', payRun='B', PAYGROUPID=18

,Period,Start Date,End Date,Process Date,Posting Date,Pay Date,Month,Posted Flag,Close Etimesheet Period,Pay Run
92,15,2026-07-12,2026-07-25,2026-07-25,2026-07-25,2026-07-25,7,N,N,B

In [9]:
import ukg_charge_rate

if payRun == 'B':
    charge_rate_df = ukg_charge_rate.main(period_control=period_control)
else:
    charge_rate_df = pd.read_csv("DataFiles/ukg_charge_rates.csv")
charge_rate_df

2026-08-06 16:56:04,787 | INFO | ukg | get request successful from endpoint_url='payroll/v1/earnings-history-base-elements'. returning 707 records.
2026-08-06 16:56:04,796 | INFO | ukg | saving 707 records to ./DataFiles/ukg_earnings_history.csv
2026-08-06 16:56:04,889 | INFO | ukg | EmpId                    string[python]
Id                                int64
CardNum                           int64
SupId                            object
SupName                          object
FirstName                        object
LastName                         object
Active                           object
Email                            object
BirthDate                        object
HireDate                         object
PayMethod                         int64
PayType                           int64
HoliRule                          int64
PayCate                           int64
PaygroupId                        int64
LocationId                        int64
JobId                             int64
ProjectId                         int64
OrgLevel1Id                       int64
OrgLevel2Id                       int64
OrgLevel3Id                       int64
OrgLevel4Id                       int64
PayPolicyId                       int64
ShiftId                           int64
AccessGroupId                     int64
OrgLevel1_Name           string[python]
OrgLevel1_Description            object
OrgLevel2_Name                   object
OrgLevel2_Description            object
OrgLevel3_Name                   object
OrgLevel3_Description            object
OrgLevel4_Name                   object
OrgLevel4_Description            object
Location_Name                    object
Location_Description             object
Paygroup_Name                    object
Paygroup_Description             object
Project_Name                     object
Project_Description              object
Job_Name                         object
Job_Description                  object
shortEmpId               string[python]
dtype: object
2026-08-06 16:56:04,896 | INFO | ukg | filtering results based on companyId='PQCD4'
2026-08-06 16:56:05,058 | INFO | ukg | writing to file. ./DataFiles/pay_classifications.csv len(df)=683
2026-08-06 16:56:05,083 | INFO | ukg | writing to file. ./DataFiles/charge_rates.csv len(df)=276
2026-08-06 16:56:05,112 | INFO | ukg | writing to file. ./DataFiles/ukg_charge_rates.csv len(df)=269
2026-08-06 16:56:05,125 | INFO | ukg | writing to file. ./DataFiles/ukg_charge_rates_202607311.csv len(df)=269

,employeeId,employeeNumber,payDate,OrgLevel1_Name,Burden,Wages,currentHours,chargeAmount,chargeRate
0,BSBDQ90210K0,001022,2026-07-31T00:00:00,90003,0.00,10117.54,80.00,0.000,0.00
1,BSBDQC00E0K0,001140,2026-07-31T00:00:00,90012,0.00,13167.90,80.00,15538.122,194.23
2,BSBDS501Y0K0,020822,2026-07-31T00:00:00,90070,4184.77,6969.23,80.00,8363.076,104.54
3,BSBDS603F0K0,020825,2026-07-31T00:00:00,90070,0.00,8560.38,80.00,10272.456,128.41
4,BSBDS80260K0,020828,2026-07-31T00:00:00,90070,0.00,9129.22,80.00,10955.064,136.94
...,...,...,...,...,...,...,...,...,...
264,GG5UFS000020,223694,2026-07-31T00:00:00,90070,0.00,8084.61,80.00,9701.532,121.27
265,GG999G000020,223695,2026-07-31T00:00:00,90070,0.00,913.28,40.59,1095.936,27.00
266,GG9HS8009020,223696,2026-07-31T00:00:00,90070,0.00,1554.52,69.09,1865.424,27.00
267,GGM6AF000020,223697,2026-07-31T00:00:00,90070,0.00,3392.31,40.00,4070.772,101.77
268,GGVHKV003020,223698,2026-07-31T00:00:00,90070,0.00,2353.84,32.00,2824.608,88.27

In [10]:
import utm_load
utm_load.load_ukg(startdate, enddate, PAYGROUPID, charge_rate_df)

from cmic import load_cmic_projects
load_cmic_projects()

2026-08-06 16:56:05,516 | INFO | utm_load | trying OrgLevel1...
2026-08-06 16:56:05,983 | INFO | utm_load | record counts for OrgLevel1:299
2026-08-06 16:56:05,985 | INFO | utm_load | trying OrgLevel2...
2026-08-06 16:56:06,254 | INFO | utm_load | record counts for OrgLevel2:600
2026-08-06 16:56:06,256 | INFO | utm_load | trying OrgLevel3...
2026-08-06 16:56:06,363 | INFO | utm_load | record counts for OrgLevel3:158
2026-08-06 16:56:06,367 | INFO | utm_load | trying OrgLevel4...
2026-08-06 16:56:06,450 | INFO | utm_load | record counts for OrgLevel4:1
2026-08-06 16:56:06,450 | INFO | utm_load | trying Location...
2026-08-06 16:56:06,582 | INFO | utm_load | record counts for Location:327
2026-08-06 16:56:06,584 | INFO | utm_load | trying Paygroup...
2026-08-06 16:56:06,677 | INFO | utm_load | record counts for Paygroup:41
2026-08-06 16:56:06,680 | INFO | utm_load | trying Project...
2026-08-06 16:56:06,845 | INFO | utm_load | record counts for Project:637
2026-08-06 16:56:06,848 | INFO | utm_load | trying Job...
2026-08-06 16:56:07,059 | INFO | utm_load | record counts for Job:1101
2026-08-06 16:56:07,061 | INFO | utm_load | trying Employee...
2026-08-06 16:56:07,062 | INFO | utm_load | main_endpoint.params=None
2026-08-06 16:56:08,055 | INFO | utm_load | record count for Employee: 2168
2026-08-06 16:56:08,056 | INFO | utm_load | trying Time...
2026-08-06 16:56:08,059 | INFO | utm_load | main_endpoint.params='$filter=WorkDate ge 2026-07-12 and WorkDate le 2026-07-25 and PaygroupId eq 18and (OrgLevel1Id eq 263 or OrgLevel1Id eq 261)'
2026-08-06 16:56:11,274 | INFO | utm_load | record count for Time: 2424
      Id OrgLevel2_Name         OrgLevel2_Description CMiC_Department
0      2         ORGLV2  Default Organization Level 2  Not Applicable
1      5         VHB03A     Vill@Castleberry Res Srvc  Not Applicable
2      6         VHB06A          Vill@Castleberry Mgr  Not Applicable
3      7         VHB07A     Vill@Castleberry Asst Mgr  Not Applicable
4      8         VHB08B        Vill@Castleberry Maint  Not Applicable
..   ...            ...                           ...             ...
595  599         12A05A         Prog. Management - CA             PMG
596  600         70A09A               Construction-NC             CGA
597  601         70A10A               Construction-FL             CFL
598  602         70A12A     Construction-Mission Crit             CMC
599  603         70A11A         Construction-Overhead             COH

[600 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Id                     600 non-null    int64
 1   OrgLevel2_Name         600 non-null    object
 2   OrgLevel2_Description  600 non-null    object
 3   CMiC_Department        600 non-null    object
dtypes: int64(1), object(3)
memory usage: 18.9+ KB
2026-08-06 16:56:11,793 | INFO | utm_load | None
2026-08-06 16:56:11,804 | INFO | cmic.CMiCAPIClient | creating instance of CMiCAPIClient
2026-08-06 16:56:11,808 | INFO | cmic.CMiCAPIClient | requesting records from jc-rest-api/rest/1/jcjob with limit=500
2026-08-06 16:56:11,810 | INFO | cmic | Requesting offset=0...
2026-08-06 16:56:12,993 | INFO | cmic.CMiCAPIClient | Retrieved 500 records — has_more=True
2026-08-06 16:56:12,993 | INFO | cmic | Requesting offset=500...
2026-08-06 16:56:14,182 | INFO | cmic.CMiCAPIClient | Retrieved 500 records — has_more=True
2026-08-06 16:56:14,182 | INFO | cmic | Requesting offset=1000...
2026-08-06 16:56:15,383 | INFO | cmic.CMiCAPIClient | Retrieved 500 records — has_more=True
2026-08-06 16:56:15,383 | INFO | cmic | Requesting offset=1500...
2026-08-06 16:56:16,244 | INFO | cmic.CMiCAPIClient | Retrieved 294 records — has_more=False
2026-08-06 16:56:16,244 | INFO | cmic.CMiCAPIClient | No more pages. Loaded 1794 items
2026-08-06 16:56:16,432 | INFO | cmic | Saved filtered project data to DataFiles/CMiC_Project_Summary.csv

In [ ]:
from cmic import employee_push
startdate_str = startdate.strftime("%Y-%m-%d")
employee_push(startdate_str)

In [ ]:
from cmic import post_timesheets_to_CMiC
import pandas as pd
import matplotlib as mpl
df_timesheet_post_results = post_timesheets_to_CMiC(payRun,testing=True)

In [ ]:
from per_diem_lumpsum import export_journal_entries
if createPerDiemEntry and payRun == 'B':
    earnings_df = pd.read_csv('./DataFiles/ukg_earnings_history.csv')
    enddate_str = enddate.strftime("%Y-%m-%d")
    export_journal_entries(earnings_df=earnings_df,pay_period_end_date=enddate_str)

In [ ]:
df_timesheet_post_results.describe(include='all')

In [ ]:
#since PostResults can contain multiple retries, filter to only most succesful attempt
filtered_post_results = df_timesheet_post_results.groupby(['Time_Id'])['Status'].idxmin()
df_filtered_post_results = df_timesheet_post_results.loc[filtered_post_results]
df_filtered_post_results

In [ ]:
plot_data = df_filtered_post_results.pivot_table(index='WorkDate',columns='Status',values='Hours',aggfunc='count')
chart = plot_data.plot(kind='bar')\
        .legend(loc=(1.05,0.5))\
        .set_title('POST Responses')
chart

In [ ]:
df_filtered_post_results.loc[df_filtered_post_results["Status"]==400]

In [ ]:
df_filtered_post_results.loc[df_timesheet_post_results["Status"]==201].count()